CREATE DATABASE IF NOT EXISTS PAYROLLSYS;


USE PAYROLLSYS;

CREATE TABLE DEPARTMENT(
    DEPARTMENTID INT NOT NULL AUTO_INCREMENT,
    DEPARTMENTNAME VARCHAR(150) NOT NULL,
    PRIMARY KEY(DEPARTMENTID)
);

CREATE TABLE PAYGRADE(
    GRADEID INT NOT NULL AUTO_INCREMENT,
    GRADENAME VARCHAR(150) NOT NULL,
    HOURLYPAY DECIMAL(6, 2) NOT NULL,
    OVERTIMEPAY DECIMAL(6, 2) DEFAULT 0.0,
    PRIMARY KEY(GRADEID)
);

CREATE TABLE EMPLOYEE(
    EMPLOYEEID INT NOT NULL AUTO_INCREMENT,
    LNAME VARCHAR(100) NOT NULL,
    FNAME VARCHAR(100) NOT NULL,
    AGE INT,
    GENDER VARCHAR(50),
    DEPARTMENTID INT NOT NULL,
    GRADEID INT NOT NULL,
    PRIMARY KEY(EMPLOYEEID),
    FOREIGN KEY (DEPARTMENTID) REFERENCES DEPARTMENT(DEPARTMENTID),
    FOREIGN KEY (GRADEID) REFERENCES PAYGRADE(GRADEID)
);

CREATE TABLE ATTENDANCE(
    ATTENDANCEID INT NOT NULL AUTO_INCREMENT,
    EMPLOYEEID INT NOT NULL,
    STARTDATE DATE NOT NULL,
    ENDDATE DATE NOT NULL,
    REGULARHOURS DECIMAL(3, 1) NOT NULL,
    OVERTIMEHOURS DECIMAL(3, 1) NOT NULL,
    PRIMARY KEY(ATTENDANCEID),
    FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE(EMPLOYEEID)
);

CREATE TABLE LEAVEREQUEST(
    LEAVEID INT NOT NULL AUTO_INCREMENT,
    EMPLOYEEID INT NOT NULL,
    STARTDATE DATE NOT NULL,
    ENDDATE DATE NOT NULL,
    PRIMARY KEY(LEAVEID),
    FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE(EMPLOYEEID)
);

CREATE TABLE ADMIN(
    ADMINID INT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(30) NOT NULL,
    USERPASSWORD VARCHAR(255) NOT NULL DEFAULT PASSWORD('12345678'),
    PRIMARY KEY(ADMINID)
);

CREATE TABLE PAYROLL(
    PAYROLLID INT NOT NULL AUTO_INCREMENT,
    EMPLOYEEID INT NOT NULL,
    STARTDATE DATE NOT NULL,
    ENDDATE DATE NOT NULL,
    GROSSSALARY DECIMAL(10, 2) NOT NULL,
    TAX  DECIMAL(10, 2) NOT NULL,
    DEDUCTIONS  DECIMAL(10, 2) NOT NULL,
    NETSALARY DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY(PAYROLLID),
    FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE(EMPLOYEEID)
);